### ISSUE TITLE
 about Data Integration Specialist Superbadge

### ISSUE THREAD

**Issue by Aygun1A** [narenoffl/PMA-Project-Salesforce#1]
Hi. Can you help me? Please send me ProjectCalloutServiceTest code

**Comment by narenoffl** [comment]
Kindly check this repository - https://github.com/narenoffl/Data-Integration-Specialist-Superbadge

**Comment by Aygun1A** [comment]
Thank you so much

**Comment by Aygun1A** [comment]
Did you complete  Advanced Apex specialist Superbadge?
